"""
Differential Diagnosis Assistant - Core Module

AI-powered diagnostic reasoning with ranked differentials, workup
recommendations, and multi-system analysis.

⚠️ MEDICAL DISCLAIMER: This tool is for EDUCATIONAL and INFORMATIONAL purposes ONLY.
It is NOT a substitute for professional medical advice, diagnosis, or treatment.
ALWAYS consult a qualified healthcare provider for any health concerns.
"""

from typing import Optional, List, Dict, Any, Tuple
import os
import sys
import logging
from datetime import datetime

# ---------------------------------------------------------------------------
# Path setup for shared common module
# ---------------------------------------------------------------------------
_common_path = os.path.join(os.path.dirname(__file__), '..', '..', '..')
sys.path.insert(0, os.path.abspath(_common_path))

from common.llm_client import chat, check_ollama_running  # noqa: E402

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logger = logging.getLogger("differential_diagnosis")


def _setup_logging(level: str = "INFO") -> None:
    """Configure logging for the differential diagnosis assistant."""
    numeric_level = getattr(logging, level.upper(), logging.INFO)
    logging.basicConfig(
        level=numeric_level,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

def load_config() -> dict:
    """Load configuration from config.yaml or use defaults."""
    config_path = os.path.join(os.path.dirname(__file__), '..', '..', 'config.yaml')
    defaults: dict = {
        "model": "gemma4",
        "temperature": 0.3,
        "max_tokens": 2048,
        "log_level": "INFO",
        "ollama_url": "http://localhost:11434",
    }
    try:
        import yaml
        with open(config_path, 'r') as f:
            user_config = yaml.safe_load(f) or {}
        defaults.update(user_config)
    except (ImportError, FileNotFoundError):
        pass
    return defaults


CONFIG = load_config()
_setup_logging(CONFIG.get("log_level", "INFO"))

# ---------------------------------------------------------------------------
# Medical disclaimer
# ---------------------------------------------------------------------------

DISCLAIMER = """
⚠️  MEDICAL DISCLAIMER  ⚠️
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This tool is for EDUCATIONAL and INFORMATIONAL purposes ONLY.
It is NOT a substitute for professional medical advice, diagnosis, or treatment.

• Do NOT use this tool to make medical decisions.
• Do NOT delay seeking professional medical care based on this tool's output.
• ALWAYS consult a qualified healthcare professional for health concerns.
• Call emergency services (911) for medical emergencies.

The differential diagnoses generated by this tool are AI-generated hypotheses
for educational purposes and must NOT be used for clinical decision-making.

By using this tool, you acknowledge that all information provided is for
educational purposes only and should not be relied upon for medical decisions.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an AI-powered differential diagnosis assistant designed for EDUCATIONAL purposes only.

IMPORTANT RULES:
1. You are NOT a doctor and CANNOT provide definitive medical diagnoses.
2. ALWAYS remind users to consult a healthcare professional.
3. Generate ranked differential diagnoses based on symptoms, patient history, and exam findings.
4. For each differential, explain the reasoning and supporting/opposing evidence.
5. If symptoms sound serious or life-threatening, strongly urge immediate medical attention.
6. Never prescribe medications or specific treatments.
7. Be systematic and thorough in your clinical reasoning.

When generating differential diagnoses:
- List conditions ranked by likelihood given the clinical picture.
- For each diagnosis, note key supporting features and features that argue against it.
- Include both common and must-not-miss diagnoses.
- Consider the patient's demographics when relevant.
- Suggest appropriate workup to differentiate between diagnoses.
- Note any red-flag symptoms that require urgent attention.

Always end your response with a reminder that this is educational information only."""

# ---------------------------------------------------------------------------
# Body system categories
# ---------------------------------------------------------------------------

BODY_SYSTEMS: Dict[str, Dict[str, Any]] = {
    "cardiovascular": {
        "symptoms": [
            "chest pain", "palpitations", "dyspnea on exertion", "orthopnea",
            "edema", "syncope", "claudication", "jugular venous distension",
        ],
        "description": "Heart and blood vessels",
    },
    "respiratory": {
        "symptoms": [
            "cough", "shortness of breath", "wheezing", "hemoptysis",
            "pleuritic pain", "sputum production", "stridor", "tachypnea",
        ],
        "description": "Lungs and airways",
    },
    "gastrointestinal": {
        "symptoms": [
            "abdominal pain", "nausea", "vomiting", "diarrhea", "constipation",
            "melena", "hematochezia", "dysphagia", "jaundice", "ascites",
        ],
        "description": "Digestive system",
    },
    "neurological": {
        "symptoms": [
            "headache", "dizziness", "seizure", "weakness", "numbness",
            "altered mental status", "vision changes", "aphasia", "tremor",
        ],
        "description": "Brain and nervous system",
    },
    "musculoskeletal": {
        "symptoms": [
            "joint pain", "back pain", "muscle weakness", "swelling",
            "stiffness", "deformity", "limited range of motion", "crepitus",
        ],
        "description": "Bones, joints, and muscles",
    },
    "endocrine": {
        "symptoms": [
            "fatigue", "weight change", "polyuria", "polydipsia",
            "heat intolerance", "cold intolerance", "hair loss", "tremor",
        ],
        "description": "Hormonal system",
    },
    "infectious": {
        "symptoms": [
            "fever", "chills", "night sweats", "lymphadenopathy",
            "malaise", "rash", "sore throat", "dysuria",
        ],
        "description": "Infections and immune response",
    },
    "psychiatric": {
        "symptoms": [
            "anxiety", "depression", "insomnia", "hallucinations",
            "suicidal ideation", "paranoia", "agitation", "confusion",
        ],
        "description": "Mental health",
    },
}

# ---------------------------------------------------------------------------
# Urgency keywords for symptom combinations
# ---------------------------------------------------------------------------

URGENCY_KEYWORDS: Dict[int, List[str]] = {
    5: [
        "chest pain", "difficulty breathing", "sudden severe headache",
        "loss of consciousness", "seizure", "stroke symptoms",
        "anaphylaxis", "suicidal ideation", "severe bleeding",
        "acute abdomen", "signs of shock", "altered mental status",
    ],
    4: [
        "high fever", "severe pain", "hemoptysis", "melena",
        "hematochezia", "severe dehydration", "acute vision loss",
        "severe abdominal pain", "rapid heartbeat", "blood in urine",
    ],
    3: [
        "moderate pain", "persistent cough", "mild fever", "recurring headache",
        "joint swelling", "persistent fatigue", "dizziness", "weight loss",
    ],
    2: [
        "mild headache", "minor cold", "mild sore throat", "mild nausea",
        "minor muscle ache", "mild fatigue", "minor skin irritation",
    ],
    1: [
        "minor scratch", "mild discomfort", "occasional sneeze", "minor bruise",
    ],
}

URGENCY_LABELS: Dict[int, Tuple[str, str]] = {
    1: ("🟢 Low", "Self-care likely sufficient. Monitor symptoms."),
    2: ("🟡 Mild", "Consider scheduling a routine appointment if symptoms persist."),
    3: ("🟠 Moderate", "Schedule an appointment with your healthcare provider soon."),
    4: ("🔴 High", "Seek medical attention promptly. Visit urgent care or your doctor today."),
    5: ("🚨 Emergency", "SEEK IMMEDIATE MEDICAL ATTENTION. Call emergency services if needed."),
}


def assess_urgency(symptoms_text: str) -> Tuple[int, str, str]:
    """Assess urgency level based on symptom keywords.

    Returns:
        (level, label, advice) where level is 1-5.
    """
    text_lower = symptoms_text.lower()
    highest_level = 1

    for level in sorted(URGENCY_KEYWORDS.keys(), reverse=True):
        for keyword in URGENCY_KEYWORDS[level]:
            if keyword in text_lower:
                if level > highest_level:
                    highest_level = level
                    logger.debug("Matched urgency keyword '%s' at level %d", keyword, level)
                break

    label, advice = URGENCY_LABELS[highest_level]
    logger.info("Urgency assessment: level=%d label=%s", highest_level, label)
    return highest_level, label, advice


def get_affected_systems(symptoms_text: str) -> List[str]:
    """Identify which body systems are affected by the described symptoms."""
    text_lower = symptoms_text.lower()
    affected: List[str] = []

    for system, data in BODY_SYSTEMS.items():
        for symptom in data["symptoms"]:
            if symptom in text_lower:
                if system not in affected:
                    affected.append(system)
                break

    if not affected:
        affected.append("general")

    logger.debug("Detected body systems: %s", affected)
    return affected


# ---------------------------------------------------------------------------
# Diagnosis session tracker
# ---------------------------------------------------------------------------

class DiagnosisSession:
    """Track diagnostic reasoning across a session."""

    def __init__(self) -> None:
        """Initialize the diagnosis session."""
        self.entries: List[Dict[str, Any]] = []

    def add_entry(
        self,
        symptoms: str,
        patient_info: str,
        exam_findings: str,
        urgency: int,
        systems: List[str],
        response: str,
    ) -> None:
        """Add a diagnostic entry to the session history."""
        entry = {
            "timestamp": datetime.now().isoformat(),
            "symptoms": symptoms,
            "patient_info": patient_info,
            "exam_findings": exam_findings,
            "urgency": urgency,
            "systems": systems,
            "response": response,
        }
        self.entries.append(entry)
        logger.info("Added session entry (total: %d)", len(self.entries))

    def get_history(self) -> List[Dict[str, Any]]:
        """Get all session entries."""
        return list(self.entries)

    def get_summary(self) -> Dict[str, Any]:
        """Get a summary of the diagnostic session."""
        if not self.entries:
            return {
                "total_consultations": 0,
                "max_urgency": 0,
                "systems_involved": [],
                "all_symptoms": [],
            }

        all_systems: List[str] = []
        all_symptoms: List[str] = []
        max_urgency = 0

        for entry in self.entries:
            for s in entry.get("systems", []):
                if s not in all_systems:
                    all_systems.append(s)
            all_symptoms.append(entry["symptoms"])
            if entry["urgency"] > max_urgency:
                max_urgency = entry["urgency"]

        return {
            "total_consultations": len(self.entries),
            "max_urgency": max_urgency,
            "systems_involved": all_systems,
            "all_symptoms": all_symptoms,
        }


# ---------------------------------------------------------------------------
# Display helpers
# ---------------------------------------------------------------------------

def display_disclaimer() -> None:
    """Display the medical disclaimer using rich formatting."""
    from rich.console import Console
    from rich.panel import Panel

    console = Console()
    console.print(Panel(DISCLAIMER, title="⚕️  Medical Disclaimer", border_style="red"))


# ---------------------------------------------------------------------------
# Differential diagnosis via LLM
# ---------------------------------------------------------------------------

def generate_differential(
    symptoms: str,
    patient_info: str = "",
    exam_findings: str = "",
    conversation_history: Optional[List[Dict[str, str]]] = None,
) -> str:
    """Generate ranked differential diagnoses using the LLM.

    Args:
        symptoms: Free-text description of presenting symptoms.
        patient_info: Patient demographics, past medical history, medications.
        exam_findings: Physical examination findings.
        conversation_history: Optional prior messages for multi-turn reasoning.

    Returns:
        LLM response with ranked differential diagnoses (educational only).
    """
    if conversation_history is None:
        conversation_history = []

    clinical_prompt = f"""Please generate a ranked differential diagnosis for the following clinical presentation:

**Presenting Symptoms:** {symptoms}
"""
    if patient_info:
        clinical_prompt += f"\n**Patient Information:** {patient_info}"
    if exam_findings:
        clinical_prompt += f"\n**Examination Findings:** {exam_findings}"

    clinical_prompt += """

Please provide:
1. A ranked list of differential diagnoses from most to least likely.
2. For each diagnosis, explain the supporting and opposing evidence.
3. Identify any red-flag features requiring urgent attention.
4. Suggest initial workup to differentiate between the top diagnoses.

Remember: This is for EDUCATIONAL purposes only."""

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.extend(conversation_history)
    messages.append({"role": "user", "content": clinical_prompt})

    logger.info("Sending differential diagnosis query to LLM (%d prior messages)", len(conversation_history))

    try:
        response = chat(messages)
        logger.info("Received LLM response (%d chars)", len(response))
        return response
    except Exception as exc:
        logger.error("LLM call failed: %s", exc)
        raise


def rank_diagnoses(diagnoses_text: str) -> str:
    """Re-rank a list of diagnoses based on clinical reasoning.

    Args:
        diagnoses_text: Text containing diagnoses to re-rank.

    Returns:
        LLM response with re-ranked diagnoses and reasoning.
    """
    prompt = f"""Please re-evaluate and re-rank the following differential diagnoses
based on clinical reasoning, prevalence, and Bayesian probability:

{diagnoses_text}

For each diagnosis, provide:
1. Updated ranking position
2. Estimated relative likelihood
3. Key distinguishing features
4. What test or finding would confirm or rule out this diagnosis

Remember: This is for EDUCATIONAL purposes only."""

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.append({"role": "user", "content": prompt})

    logger.info("Sending re-ranking query to LLM")

    try:
        response = chat(messages)
        logger.info("Received re-ranking response (%d chars)", len(response))
        return response
    except Exception as exc:
        logger.error("Re-ranking LLM call failed: %s", exc)
        raise


def get_workup_recommendations(diagnosis: str) -> str:
    """Get recommended workup for a specific diagnosis.

    Args:
        diagnosis: The diagnosis to get workup recommendations for.

    Returns:
        LLM response with recommended diagnostic workup.
    """
    prompt = f"""For the suspected diagnosis of **{diagnosis}**, please recommend
an appropriate diagnostic workup:

1. **First-line investigations** — Initial labs, imaging, or tests to order.
2. **Second-line investigations** — If first-line is inconclusive.
3. **Specialist referrals** — When and which specialists to consider.
4. **Key findings to look for** — What results would confirm or refute this diagnosis.
5. **Differential to keep in mind** — Other diagnoses these tests might reveal.

Remember: This is for EDUCATIONAL purposes only."""

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.append({"role": "user", "content": prompt})

    logger.info("Sending workup recommendation query for: %s", diagnosis)

    try:
        response = chat(messages)
        logger.info("Received workup response (%d chars)", len(response))
        return response
    except Exception as exc:
        logger.error("Workup LLM call failed: %s", exc)
        raise


def compare_diagnoses(
    diagnosis1: str,
    diagnosis2: str,
    clinical_data: str = "",
) -> str:
    """Compare two diagnoses in the context of clinical data.

    Args:
        diagnosis1: First diagnosis to compare.
        diagnosis2: Second diagnosis to compare.
        clinical_data: Clinical context for comparison.

    Returns:
        LLM response comparing the two diagnoses.
    """
    prompt = f"""Please compare and contrast the following two diagnoses:

**Diagnosis 1:** {diagnosis1}
**Diagnosis 2:** {diagnosis2}
"""
    if clinical_data:
        prompt += f"\n**Clinical Context:** {clinical_data}"

    prompt += """

Please provide:
1. **Key distinguishing features** between the two diagnoses.
2. **Shared features** that make them difficult to differentiate.
3. **Diagnostic tests** that would help distinguish between them.
4. **Clinical pearls** for differentiating these conditions.
5. **Which is more likely** given the clinical context (if provided).

Remember: This is for EDUCATIONAL purposes only."""

    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages.append({"role": "user", "content": prompt})

    logger.info("Sending diagnosis comparison query: %s vs %s", diagnosis1, diagnosis2)

    try:
        response = chat(messages)
        logger.info("Received comparison response (%d chars)", len(response))
        return response
    except Exception as exc:
        logger.error("Comparison LLM call failed: %s", exc)
        raise
